repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.7
    hooks:
      - id: ruff-format
      - id: ruff
        args: [--fix, --unsafe-fixes, --exit-non-zero-on-fix]

  - repo: local
    hooks:
      # - id: pyright
      #   name: pyright
      #   entry: uv run pyright
      #   language: system
      #   types: [python]
      #   pass_filenames: false

      - id: ty
        name: ty check
        entry: uv run ty check .
        language: system
        pass_filenames: false
        always_run: true

      - id: pytest
        name: pytest
        entry: bash -c "PYTHONPATH=. uv run pytest"
        language: system
        types: [python]
        pass_filenames: false
